
class ActivityType:
    POSTURE = 0
    SLOUCH_ALERT = 1
    SIT_ALERT = 2
    WALKING = 3
    WALKING_UPSTAIRS = 4
    WALKING_DOWNSTAIRS = 5
    SITTING = 6
    STANDING = 7
    LAYING = 8
    STAND_TO_SIT = 9
    SIT_TO_STAND = 10
    SIT_TO_LIE = 11
    LIE_TO_SIT = 12
    STAND_TO_LIE = 13
    LIE_TO_STAND = 14
